monitoring_root: /opt/monitoring

prometheus_host_port: 9091

pve_exporter_host_port: 9221
pve_user: "prometheus@pve"
pve_token_name: "monitoring"
pve_verify_ssl: false

monitor_proxmox: true
monitor_node_exporter: true
monitor_smartctl: true
monitor_ceph: true

alertmanager_host_port: 9093
alertmanager_smtp_host: localhost
alertmanager_smtp_port: 25
alertmanager_smtp_username: '' #To authenticate to local/public smtp server, when applicable
alertmanager_smtp_password: ''
alertmanager_send_email: 'localhost@localhost'
alertmanager_receive_email:
  - 'localhost@localhost'
  - 'dummy@localhost'
alertmanager_require_tls: 'false'

grafana_host_port: 3000
grafana_admin_user: admin
grafana_admin_password: admin
grafana_dashboards:
  - dashboard_id: 1860
    revision: 37
    datasource: Prometheus
  - dashboard_id: 9550
    revision: 1
    datasource: Prometheus
